# Generated by Django 5.1 on 2024-08-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dronefleet', '0002_alter_drone_options_alter_pilot_options_competition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ('-distance_in_metres',)},
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='distance_in_feet',
            new_name='distance_in_metres',
        ),
    ]
